<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TipoRemitente extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::table('cat_remitentes')->insert([
            [
                'categoria'   => 'Juzgado',
                'dependencia' => 'Juzgado Primero de lo Civil',
                'remitente'   => 'Lic. Ana Torres Hernández',
                'cargo'       => 'Jueza',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Juzgado',
                'dependencia' => 'Juzgado Segundo Penal',
                'remitente'   => 'Lic. Luis Mendoza García',
                'cargo'       => 'Juez',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Secretaría',
                'dependencia' => 'Secretaría de Acuerdos',
                'remitente'   => 'Lic. Jorge Martínez Ruiz',
                'cargo'       => 'Secretario de Acuerdos',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Tribunal',
                'dependencia' => 'Tribunal Superior de Justicia',
                'remitente'   => 'Dra. María López Gómez',
                'cargo'       => 'Magistrada',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Tribunal',
                'dependencia' => 'Tribunal de Enjuiciamiento',
                'remitente'   => 'Dr. Ernesto Ramírez Zárate',
                'cargo'       => 'Magistrado',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Ministerio Público',
                'dependencia' => 'Fiscalía General del Estado',
                'remitente'   => 'Lic. Rafael Díaz Soto',
                'cargo'       => 'Agente del Ministerio Público',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Unidad de Gestión',
                'dependencia' => 'Unidad de Gestión Judicial 1',
                'remitente'   => 'C. Erika Salgado Pérez',
                'cargo'       => 'Coordinadora',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Defensoría',
                'dependencia' => 'Defensoría Pública del Estado',
                'remitente'   => 'Lic. Mario Rivera Téllez',
                'cargo'       => 'Defensor Público',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Archivo Judicial',
                'dependencia' => 'Archivo General del Poder Judicial',
                'remitente'   => 'C. Laura Peña Bravo',
                'cargo'       => 'Encargada de Archivo',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Notificación',
                'dependencia' => 'Oficialía de Partes',
                'remitente'   => 'Lic. Hugo Escobar Medina',
                'cargo'       => 'Notificador Judicial',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Juzgado',
                'dependencia' => 'Juzgado Tercero de lo Familiar',
                'remitente'   => 'Lic. Carmen Ríos Velázquez',
                'cargo'       => 'Jueza',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Secretaría',
                'dependencia' => 'Secretaría Técnica del Consejo',
                'remitente'   => 'Lic. Alberto Luna Cabrera',
                'cargo'       => 'Secretario Técnico',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Tribunal',
                'dependencia' => 'Tribunal Electoral del Estado',
                'remitente'   => 'Mtra. Rosario Aguilar González',
                'cargo'       => 'Magistrada Presidenta',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Ministerio Público',
                'dependencia' => 'Agencia del MP Especializada en Delitos Sexuales',
                'remitente'   => 'Lic. Benjamín Silva Torres',
                'cargo'       => 'Agente del MP',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Unidad de Gestión',
                'dependencia' => 'Unidad de Gestión Judicial 2',
                'remitente'   => 'C. Mónica Salas Cruz',
                'cargo'       => 'Coordinadora Administrativa',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Defensoría',
                'dependencia' => 'Defensoría Penal Especializada',
                'remitente'   => 'Lic. Óscar Mejía Delgado',
                'cargo'       => 'Defensor Público Penal',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Archivo Judicial',
                'dependencia' => 'Centro de Resguardo de Evidencias',
                'remitente'   => 'C. Paula Méndez Ruiz',
                'cargo'       => 'Responsable de Evidencias',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Notificación',
                'dependencia' => 'Oficialía de Partes Común',
                'remitente'   => 'Lic. Gerardo Jiménez Vela',
                'cargo'       => 'Notificador Adscrito',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Juzgado',
                'dependencia' => 'Juzgado Mixto de Huajuapan',
                'remitente'   => 'Lic. Itzel Morales Domínguez',
                'cargo'       => 'Jueza de Control',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Tribunal',
                'dependencia' => 'Sala de Justicia para Adolescentes',
                'remitente'   => 'Dr. Fernando Ríos Castillo',
                'cargo'       => 'Magistrado Especializado',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Juzgado',
                'dependencia' => 'Juzgado Cuarto de lo Penal',
                'remitente'   => 'Lic. Juan Carlos Pérez Ruiz',
                'cargo'       => 'Juez',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Secretaría',
                'dependencia' => 'Secretaría Ejecutiva del Pleno',
                'remitente'   => 'Lic. Sofía Vargas Ramírez',
                'cargo'       => 'Secretaria Ejecutiva',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Tribunal',
                'dependencia' => 'Tribunal de Justicia Administrativa',
                'remitente'   => 'Mtro. Guillermo Chávez López',
                'cargo'       => 'Magistrado',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Ministerio Público',
                'dependencia' => 'Unidad Especializada en Homicidios',
                'remitente'   => 'Lic. Mariela Gómez Pineda',
                'cargo'       => 'Agente del Ministerio Público',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Unidad de Gestión',
                'dependencia' => 'Unidad de Gestión Judicial 3',
                'remitente'   => 'C. Teresa Ramírez Castillo',
                'cargo'       => 'Coordinadora',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Defensoría',
                'dependencia' => 'Defensoría de Oficio de Oaxaca Centro',
                'remitente'   => 'Lic. Hugo Alberto Martínez',
                'cargo'       => 'Defensor Público',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Archivo Judicial',
                'dependencia' => 'Archivo Regional de Valles Centrales',
                'remitente'   => 'C. Mónica Torres Salinas',
                'cargo'       => 'Archivista',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Notificación',
                'dependencia' => 'Oficialía de Partes Penal',
                'remitente'   => 'Lic. Carlos Rivera Beltrán',
                'cargo'       => 'Notificador Judicial',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Juzgado',
                'dependencia' => 'Juzgado Mixto de Tlaxiaco',
                'remitente'   => 'Lic. Andrea Molina López',
                'cargo'       => 'Jueza',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Tribunal',
                'dependencia' => 'Tribunal de Alzada Penal',
                'remitente'   => 'Dr. Víctor Sánchez Morales',
                'cargo'       => 'Magistrado Ponente',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],

            [
                'categoria'   => 'Juzgado',
                'dependencia' => 'Juzgado Familiar de Oaxaca',
                'remitente'   => 'Lic. Patricia Luna García',
                'cargo'       => 'Jueza',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Secretaría',
                'dependencia' => 'Secretaría de Servicios Judiciales',
                'remitente'   => 'Lic. Héctor Ramírez Figueroa',
                'cargo'       => 'Secretario General',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Tribunal',
                'dependencia' => 'Tribunal Laboral del Estado',
                'remitente'   => 'Lic. Sandra López Ruiz',
                'cargo'       => 'Magistrada Presidenta',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Ministerio Público',
                'dependencia' => 'Fiscalía de Delitos Sexuales',
                'remitente'   => 'Lic. Mario Quiroz Hernández',
                'cargo'       => 'Fiscal Especializado',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Unidad de Gestión',
                'dependencia' => 'Unidad de Gestión Judicial 5',
                'remitente'   => 'C. Norma Pérez Silva',
                'cargo'       => 'Encargada de Unidad',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Defensoría',
                'dependencia' => 'Defensoría Penal de Tehuantepec',
                'remitente'   => 'Lic. Armando Salinas Pérez',
                'cargo'       => 'Defensor Público',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Archivo Judicial',
                'dependencia' => 'Archivo de la Región Mixteca',
                'remitente'   => 'C. Gabriela Molina Reyes',
                'cargo'       => 'Jefa de Archivo',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Notificación',
                'dependencia' => 'Notificaciones Civiles Oaxaca Centro',
                'remitente'   => 'Lic. Álvaro Méndez Ríos',
                'cargo'       => 'Notificador',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Juzgado',
                'dependencia' => 'Juzgado Tercero de lo Mercantil',
                'remitente'   => 'Lic. Rosa María Torres León',
                'cargo'       => 'Jueza',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'categoria'   => 'Tribunal',
                'dependencia' => 'Tribunal de Responsabilidades Administrativas',
                'remitente'   => 'Dr. Óscar Domínguez Cruz',
                'cargo'       => 'Magistrado Instructor',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
        ]);
    }
}
